In [1]:
import pandas as pd
import numpy as np

In [2]:
from sklearn.datasets import load_diabetes


In [3]:
data=load_diabetes()

In [4]:
X=data.data

In [5]:
X

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990842, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06832974, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286377, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04687948,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452837, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00421986,  0.00306441]])

In [6]:
Y=data.target

In [7]:
Y

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 28

In [8]:
np.identity(X.shape[1])

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [9]:
def ridge_regression(X,Y,alpha):
    n=X.shape[0]
    Xv=np.c_[np.ones((n,1)),X]
    theta=np.linalg.inv((Xv.T@Xv)+(alpha*np.identity(Xv.shape[1])))@(Xv.T@Y)
    return theta

In [10]:
theta=ridge_regression(X,Y,1)

In [11]:
def predict(X,theta):
    n=X.shape[0]
    Xv=np.c_[np.ones((n,1)),X]
    return Xv@theta

In [166]:
theta=ridge_regression(X,Y,0.000001)
yp=predict(X,theta)

In [167]:
ymean=np.mean(Y)

In [168]:
ymean

152.13348416289594

yp

In [169]:
r2_square=np.sum((yp-ymean)**2)/np.sum((Y-ymean)**2)

In [170]:
r2_square*100

51.77479769098491

In [25]:
from sklearn.model_selection import train_test_split

In [138]:
Xtrain,xtest,ytrain,ytest=train_test_split(X,Y,test_size=0.7)

In [139]:
theta=ridge_regression(Xtrain,ytrain,0.00001)

In [140]:
yp=predict(xtest,theta)

In [141]:
ymean=np.mean(ytest)

In [142]:
r2_square=np.sum((yp-ymean)**2)/np.sum((ytest-ymean)**2)

In [143]:
r2_square*100

59.70126175079889

In [101]:
%matplotlib  inline
import matplotlib.pyplot as plt