In [2]:
import numpy as np


####  Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [3]:
arr1=np.arange(1,6*7*8+1)

In [4]:
arr1=arr1.reshape(6,7,8)

In [5]:
arr1[1,5,3]

100

#### Normalize a 5x5 random matrix

In [9]:
arr2=np.random.rand(5,5)

In [10]:
arr2/np.sum(arr2)

array([[0.08351065, 0.02895056, 0.0086903 , 0.00077189, 0.02868275],
       [0.08157862, 0.07167703, 0.01607305, 0.0461384 , 0.03755533],
       [0.01303789, 0.03225962, 0.00292429, 0.02656415, 0.098405  ],
       [0.0474458 , 0.01361695, 0.08711798, 0.04079771, 0.02878203],
       [0.01311603, 0.00260022, 0.08384652, 0.08516793, 0.0206893 ]])

#### Multiply a 5x3 matrix by a 3x2 matrix

In [12]:
np.ones((5,3)).dot(np.ones((3,2)))

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

#### Given a 1D array, negate all elements which are between 3 and 8, in place.

In [13]:
arr3=np.arange(10,20)

In [14]:
arr3[3:8]=arr3[3:8]*-1

In [15]:
arr3

array([ 10,  11,  12, -13, -14, -15, -16, -17,  18,  19])