In [1]:
import numpy as np

In [2]:
np.__version__

'1.16.4'

#### Create a null vector of size 10

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### How to find the memory size of any array 

In [4]:
np.zeros(10).size

10

#### Create a null vector of size 10 but the fifth value which is 1

In [5]:
arr=np.zeros(10)

In [6]:
arr[4]=1

In [7]:
arr

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### Create a vector with values ranging from 10 to 49

In [8]:
arr1=np.arange(10,49)

#### Reverse a vector (first element becomes last)

In [9]:
arr1[-1::-1]

array([48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [10]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Find indices of non-zero elements from [1,2,0,0,4,0]

In [11]:
arr2=np.array([1,2,0,0,4,0])

In [12]:
arr2[arr2>0]

array([1, 2, 4])

#### Create a 3x3 identity matrix

In [13]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Create a 3x3x3 array with random values

In [14]:
np.random.randn(3,3,3)

array([[[-0.86381805, -1.20256189,  0.96790953],
        [-1.15570892, -2.8132288 ,  0.52377594],
        [ 0.67445612,  2.16607261,  0.11507761]],

       [[ 0.42379516,  1.46005788,  0.12748379],
        [-0.59010704,  0.2225545 ,  0.06827732],
        [ 2.17474139, -1.3559706 , -1.14436619]],

       [[-0.61558113,  1.71675226,  0.42511546],
        [ 1.17328701, -1.93847975,  0.7217617 ],
        [ 0.58881404, -0.06476045, -0.154567  ]]])

#### Create a 10x10 array with random values and find the minimum and maximum values

In [15]:
np.random.randn(10,10).max()

2.519002425619338

#### Create a random vector of size 30 and find the mean value

In [16]:
np.random.randn(30).mean()

-0.16939484843575295

#### Create a 2d array with 1 on the border and 0 inside 

In [17]:
arr3=np.ones((5,5))

In [18]:
arr3[1:-1,1:-1]=0

In [19]:
arr3

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [20]:
0*np.nan

nan

In [21]:
np.nan== np.nan

False

In [22]:
np.inf > np.nan

False

In [23]:
np.nan - np.nan

nan

In [24]:
np.nan in set([np.nan])

True

In [25]:
0.3 == 3 * 0.1

False

In [26]:
3*0.1

0.30000000000000004

#### Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [27]:
np.diag([1,2,3,4,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

#### Create a 8x8 matrix and fill it with a checkerboard pattern

In [28]:
arr5=np.zeros((8,8))

In [29]:
arr5[0::2,::2]=1

In [30]:
arr5[1::2,1::2]=1

In [31]:
arr5

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])